### ISSUE TITLE
[Feature Request] sender as ToolbarItem

### ISSUE THREAD

**Issue by rdaniel0** [SKLn-Rad/Xam.Plugin.PopupMenu#1]
Support sender as ToolbarItem so a popup menu can be created from a toolbar item.

**Comment by rraallvv** [comment]
I tried to use this for a toolbar item, and it turns out that effects won't work with those. When some effect is attached to the control the callbacks OnAttached and OnDetached are not called.

Also I couldn't find a way to get the bounding rect for the toolbar item from the native side on iOS, in order to pass that to the popover.

An alternative could be to have a custom page or navigation renderer that converts secondary items in the toolbar into a popover menu for iOS (Android already has that feature built-in).

**Comment by rdaniel0** [comment]
The custom page is the route I ended up going with. It is rather hacky though so I'll eventually replace that with a custom navigation renderer implementation.

Regardless, thanks for taking the time to investigate.
